apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 368763425814.dkr.ecr.us-east-1.amazonaws.com/frontend:b594c5c07bc7936211db050182a2b6b515e695d1
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://gateway:3001/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: boutique
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

